### PR TITLE
New implementations on fast/slow learner problems

### PR DESCRIPTION
**Pull request by haoyuan-l**
To do:

1. Still working on the fast/slow memory problems, existing some problems on data labeling.
2. More work on the GP_memory script needs to be done...

### CODE REVIEW

**Comment by haoyuan-l** [comment]
To reproduce the result:

1. Run data preprocessing: Data Preprocessing/dataCleaning.ipynb ==> Data Preprocessing/dataCollection.ipynb
2. Run data collection for time series data ==> GP_model/ts_dataCollection_learner.ipynb
3. Run data preparation for time series data ==> GP_model/ts_dataPreparation _learner.ipynb
4. Run the GPC model for learner problem ==> GP_model/gp _learner.ipynb

**Review by TKlingstrom — DISMISSED** [review]
in ts_dataCollection_learner.ipynb.

The code in line 37 only seem to work only for one farm, generalising it would allow us to rerun the script on multiple farms as we accumulate longer data series and add more farms manually. I hope to do this in January and having the code ready for this would save a lot of time. Basically we will add data from September to January and two more farms.

Also, how is good or bad memory defined?

**Comment by haoyuan-l** [comment]
> in ts_dataCollection_learner.ipynb.
> 
> The code in line 37 only seem to work only for one farm, generalising it would allow us to rerun the script on multiple farms as we accumulate longer data series and add more farms manually. I hope to do this in January and having the code ready for this would save a lot of time. Basically we will add data from September to January and two more farms.
> 
> Also, how is good or bad memory defined?
@TKlingstrom 
That part of the data chunk is only a prototype for initial analysis. You can see the generalized implementation in the memory script, and I wrap this part into an executable function.
image

For the good/bad memory problem, the good news is I have initial results based on the method I discussed with Salman at the last meeting. But the result needs to be fine-tuned (e.g. feature selection and kernel parameters). 
I will push new commits later next week. These days I have to write my thesis project specification and other writing materials.

**Comment by haoyuan-l** [comment]
This branch needs more commits before merging into the main branch.🎯

**Comment by haoyuan-l** [comment]
After everything is settled, I will transform these IPython files into executable python scripts.

**Review by TKlingstrom — APPROVED** [review]
Approved by meeting 2023-02-02

**Pull request merged**
